services:
  postgres:
    image: 'postgres:16'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=loving_appointment_db'
      - 'POSTGRES_USER=appointment_service'
      - 'POSTGRES_PASSWORD=appointment_service_pass'
    ports:
      - '5436:5432'
    volumes:
      - appointment_pgdata:/var/lib/postgresql/data

volumes:
  appointment_pgdata:
    driver: local