services:
  postgres:
    image: 'postgres:16'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=loving_auth_db'
      - 'POSTGRES_USER=auth_service'
      - 'POSTGRES_PASSWORD=auth_service_pass'
    ports:
      - '5434:5432'
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
volumes:
  auth_pgdata:
    driver: local