services:
  postgres:
    image: 'postgres:16'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=loving_users_db'
      - 'POSTGRES_USER=user_service'
      - 'POSTGRES_PASSWORD=user_service_pass'
    ports:
      - '5435:5432'
    volumes:
      - user_pgdata:/var/lib/postgresql/data

volumes:
  user_pgdata:
    driver: local